### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by kate-fsd** [wzdorowa/TOXIN#28]
Это нужно поправить
![image](https://user-images.githubusercontent.com/66846004/130858912-fcb25010-9518-4b8d-a398-41a7c4dca872.png)

**Comment by kate-fsd** [comment]
Отступы
![image](https://user-images.githubusercontent.com/66846004/132048153-6d16d3bd-0657-4ae9-82d1-0655b22fbb54.png)

![image](https://user-images.githubusercontent.com/66846004/132048181-18b1fb79-f8e0-4d84-a25b-c1b110205f64.png)

Между блоками с информацией. Сейчас заголовок ближе к чужому блоку чем к своему
![image](https://user-images.githubusercontent.com/66846004/132048354-f07e462a-7193-4ce0-9c0f-b34c84a6201a.png)

![image](https://user-images.githubusercontent.com/66846004/132048410-3e1382c2-b7cc-41c4-a1cb-3220431d4b0a.png)

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/132048501-d00ae6ec-60d9-4280-9c6c-7c9c8dcc4b6a.png)

**Comment by kate-fsd** [comment]
Лучше сделать чтоб они не скакали. И отступ
![Peek 2021-09-03 21-04](https://user-images.githubusercontent.com/66846004/132048609-1ee86402-6687-485e-9a07-cd010673aa2f.gif)

**Comment by kate-fsd** [comment]
Тут тоже высота немного прыгает
![Peek 2021-09-03 21-07](https://user-images.githubusercontent.com/66846004/132048862-16650849-a8eb-497d-97f4-876502f4380a.gif)

**Comment by kate-fsd** [comment]
У хэдера должна быть тень
![image](https://user-images.githubusercontent.com/66846004/132049535-9ed24f8b-1131-4965-b0db-43a53bf55d79.png)

**Comment by kate-fsd** [comment]
Здесь тоже
![image](https://user-images.githubusercontent.com/66846004/132049589-00358e22-2cbe-49c1-b8aa-59f8e16e7a25.png)

**Comment by kate-fsd** [comment]
В макете полоски длиннее
![image](https://user-images.githubusercontent.com/66846004/132049741-1aeb62cd-1556-41d8-ace2-222382cfe9a9.png)

**Comment by kate-fsd** [comment]
Все заголовки с разными горизонтальными отступами, смотрится не очень. И вертикальные)
![image](https://user-images.githubusercontent.com/66846004/132050413-ebb1bb42-3ab8-4a04-bdec-844275e33677.png)

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/132050585-620f21b0-964f-413b-a572-ce798006cece.png)

**Comment by kate-fsd** [comment]
Тоже стоит отсуп добавить
![image](https://user-images.githubusercontent.com/66846004/132051956-6bdebd73-52c3-488f-87af-ef99b631956c.png)

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/132052033-4b05a4d3-a87c-4b36-8c5b-3c93fa5016e8.png)

**Comment by kate-fsd** [comment]
стрелка не в ту сторону
![image](https://user-images.githubusercontent.com/66846004/132052206-f11b84e3-0e52-49c0-aab2-bf36f59ac700.png)

**Comment by wzdorowa** [comment]
> стрелка не в ту сторону
> ![image](https://user-images.githubusercontent.com/66846004/132052206-f11b84e3-0e52-49c0-aab2-bf36f59ac700.png)

в макете вроде такое же направление стрелки. или я что-то путаю?
![Снимок экрана 2021-09-07 в 18 36 05](https://user-images.githubusercontent.com/45556339/132372663-32266eb8-2179-43fb-807b-59e6032414b0.png)

**Comment by kate-fsd** [comment]
> Отступы
> ![image](https://user-images.githubusercontent.com/66846004/132048153-6d16d3bd-0657-4ae9-82d1-0655b22fbb54.png)

не сделано

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/132948400-1e2257a6-f2a6-4887-bbaa-1e911315e3d2.png)

**Comment by kate-fsd** [comment]
> Все заголовки с разными горизонтальными отступами, смотрится не очень. И вертикальные)
> ![image](https://user-images.githubusercontent.com/66846004/132050413-ebb1bb42-3ab8-4a04-bdec-844275e33677.png)

Остались разными. Обрати внимание на это правило и последнее предложение https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#1.13

**Comment by kate-fsd** [comment]
Поправляй замечания сразу по всему проекту, я еще вижу пару проблем с отступами

**Comment by kate-fsd** [comment]
> в макете вроде такое же направление стрелки. или я что-то путаю?

Посмотри на направление когда открыто закрыто

**Comment by kate-fsd** [comment]
Текст прыгает
![Peek 2021-09-11 17-11](https://user-images.githubusercontent.com/66846004/132950730-829d69cc-1304-4400-ab6e-bbb2b24e7aff.gif)

**Comment by wzdorowa** [comment]
> Текст прыгает
> ![Peek 2021-09-11 17-11](https://user-images.githubusercontent.com/66846004/132950730-829d69cc-1304-4400-ab6e-bbb2b24e7aff.gif)


https://user-images.githubusercontent.com/45556339/133442589-b9d3a000-2ab7-4374-84ba-36cc3d64e338.mov

Теперь не должен

**Comment by kate-fsd** [comment]
В макете при достижении граничных значений кнопки светлее
![image](https://user-images.githubusercontent.com/66846004/148766665-40c11484-773b-49ab-9df7-0381b3cdcee7.png)

**Comment by kate-fsd** [comment]
Цвет текста
![image](https://user-images.githubusercontent.com/66846004/148766795-cd1c7adb-c374-444f-a01c-0111bfaacfd0.png)

**Comment by kate-fsd** [comment]
Нет тени хэдера
![image](https://user-images.githubusercontent.com/66846004/148767045-8771782a-41bb-44e7-9d83-2e9a8409cb0b.png)

**Comment by kate-fsd** [comment]
Разные стрелочки
![image](https://user-images.githubusercontent.com/66846004/148767484-5958a326-eef3-41e4-b5a4-44ed31e4fe4f.png)

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/148767867-4c098a65-7ffd-4811-8b34-0f0f55318932.png)

**Comment by kate-fsd** [comment]
Отступ
![image](https://user-images.githubusercontent.com/66846004/148767998-40a0238d-a447-40f5-b336-df59a6134943.png)

**Comment by kate-fsd** [comment]
Нужно число должно быть отцентрировано
![image](https://user-images.githubusercontent.com/66846004/148772193-283c1b0c-400d-41a5-bf66-033c2472ad8c.png)

**Comment by kate-fsd** [comment]
На странице room-details лучше ограничить по высоте картинки (по желанию)
![image](https://user-images.githubusercontent.com/66846004/148772597-4fbb4f40-9194-438a-bfed-e1cd19383bd0.png)

**Comment by wzdorowa** [comment]
> Разные стрелочки 

![image](https://user-images.githubusercontent.com/66846004/148767484-5958a326-eef3-41e4-b5a4-44ed31e4fe4f.png)


не нашла( вроде везде одинаковые 

![Снимок экрана 2022-01-18 в 14 29 31](https://user-images.githubusercontent.com/45556339/149929455-96e30572-b04e-41de-90be-331c8bd82aa1.png)

**Comment by kate-fsd** [comment]
> не нашла( вроде везде одинаковые

![image](https://user-images.githubusercontent.com/66846004/150155686-c5071700-e30a-45c6-b71b-2070ae7e79d2.png)
![image](https://user-images.githubusercontent.com/66846004/150155751-ad810ba6-3a55-4a6c-9ee5-2cabaa114b31.png)

По макету должны быть тоненькие
