### ISSUE TITLE
Pixel perfect

### ISSUE THREAD

**Issue by kate-fsd** [wzdorowa/TOXIN#29]
![image](https://user-images.githubusercontent.com/66846004/130859263-b3a38fa8-72bb-44e4-9268-a346a63285b7.png)

Кнопки +- не круглые
У кнопок применить и очистить шрифт меньше чем в макете
Граница должна быть одинаковой
Нет тени

**Comment by kate-fsd** [comment]
Если у тебя нет расхождении, скинь пожалуйста свои картинки. Или можешь их прямо проект добавить
![image](https://user-images.githubusercontent.com/66846004/132051045-721ab3fd-a786-4664-b121-c3af5d850ac0.png)

**Comment by kate-fsd** [comment]
Такого расхождения в простом компоненте не должно быть
![Peek 2021-09-03 21-29](https://user-images.githubusercontent.com/66846004/132051111-381597b9-5624-45ab-9f63-43bd46fa9957.gif)

**Comment by kate-fsd** [comment]
Градиент
![image](https://user-images.githubusercontent.com/66846004/132051576-f6e5077a-504b-4de2-b6f4-a1e0cc9f3954.png)

**Comment by wzdorowa** [comment]
![Landing-page](https://user-images.githubusercontent.com/45556339/132099179-34d7f9a6-62bd-4301-b4d2-c5bedac2d5b5.png)

**Comment by wzdorowa** [comment]
![Search-room-page](https://user-images.githubusercontent.com/45556339/132099204-5c39c48c-1555-4e07-9372-801b1285c8da.png)

**Comment by wzdorowa** [comment]
![Room-details-page](https://user-images.githubusercontent.com/45556339/132099224-285b07b9-d52a-4366-bccb-228cce8187d1.png)

**Comment by wzdorowa** [comment]
![Sign-in-page](https://user-images.githubusercontent.com/45556339/132099232-96292e27-77a8-4ef0-8f09-2d41bc842ea3.png)

**Comment by wzdorowa** [comment]
Вот здесь самые большие расхождения, я считаю, но только потому что margin слева и справа выставлены автоматические. можно сделать лучше, если подгонять отступы вручную.

![Registration-page](https://user-images.githubusercontent.com/45556339/132099239-fd1a29c1-5795-40de-a17d-9ede83b4d233.png)

**Comment by kate-fsd** [comment]
Кнопки
![image](https://user-images.githubusercontent.com/66846004/132948637-8bcc5f2a-8859-4dac-8b84-d24e13ea009c.png)

**Comment by kate-fsd** [comment]
Я имею в виду картинки самих макетов, по которым ты сверяешься, чтобы я тоже могла сверить

**Comment by kate-fsd** [comment]
![Peek 2021-09-11 16-40](https://user-images.githubusercontent.com/66846004/132949892-2b22ec71-944e-4b7b-bf09-37a42743f9d3.gif)

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/132949934-0d45e9bf-406c-4399-9b39-d121041a518f.png)

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/132950691-e805854a-5de2-4dc5-ba77-0494acef1283.png)

**Comment by kate-fsd** [comment]
Размер шрифта
![image](https://user-images.githubusercontent.com/66846004/132950821-e2141290-c891-45a7-a024-e46df8c1d508.png)

**Comment by kate-fsd** [comment]
> Проверь размеры шрифтов, есть расхождения

Еще раз)

**Comment by wzdorowa** [comment]
сделала deploy - данные на gh-pages обновились
![Снимок экрана 2021-09-15 в 17 14 40](https://user-images.githubusercontent.com/45556339/133450326-b668b088-43c7-4d7f-97bd-bc5af38e5b19.png)

**Comment by kate-fsd** [comment]
Есть расхождения который стоит исправить
![image](https://user-images.githubusercontent.com/66846004/148773493-49011bb3-ed7c-4a80-90d9-d84a67cb499e.png)
![image](https://user-images.githubusercontent.com/66846004/148773537-eedf6c4e-7d41-4157-88e3-8f576524676d.png)
![image](https://user-images.githubusercontent.com/66846004/148773650-6d85c7a1-3384-4513-b36a-d7be48e99781.png)
и подобное

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/148775474-313566d8-ac34-4948-bdf0-69bcfc49f376.png)

**Comment by kate-fsd** [comment]
Есть несоответствия макету
![image](https://user-images.githubusercontent.com/66846004/151601875-e5f4e050-7b2d-41ce-8fa3-1fbe35dc4f65.png)

**Comment by kate-fsd** [comment]
Поправь тут вертикальное выравнивание
![image](https://user-images.githubusercontent.com/66846004/151602300-22bea6a4-128c-4507-9dbb-0b741e1384da.png)

**Comment by kate-fsd** [comment]
Карточки серые
![image](https://user-images.githubusercontent.com/66846004/151603281-b386cd7e-978f-45e3-a9b3-8c6975e393a1.png)

**Comment by kate-fsd** [comment]
Цвет
![image](https://user-images.githubusercontent.com/66846004/151604270-6f045659-f116-473a-bc2e-487d40473c34.png)

**Comment by kate-fsd** [comment]
> Есть несоответствия макету ![image](https://user-images.githubusercontent.com/66846004/151601875-e5f4e050-7b2d-41ce-8fa3-1fbe35dc4f65.png)

Осталось

**Comment by kate-fsd** [comment]
В карточках комнат добавь еще border-radius

**Comment by kate-fsd** [comment]
> > Есть несоответствия макету ![image](https://user-images.githubusercontent.com/66846004/151601875-e5f4e050-7b2d-41ce-8fa3-1fbe35dc4f65.png)
> 
> Осталось

Еще не все. Обновляй пожалуйста gh-pages

**Comment by wzdorowa** [comment]
Обновила gh-pages.

**Comment by kate-fsd** [comment]
> > > Есть несоответствия макету ![image](https://user-images.githubusercontent.com/66846004/151601875-e5f4e050-7b2d-41ce-8fa3-1fbe35dc4f65.png)
> > 
> > 
> > Осталось
> 
> Еще не все. Обновляй пожалуйста gh-pages

Стрелки в макете больше, я ишью закрою, но исправь пожалуйста
