### ISSUE TITLE
Компонент

### ISSUE THREAD

**Issue by kate-fsd** [wzdorowa/TOXIN#37]
![image](https://user-images.githubusercontent.com/66846004/132950971-7a9e89f7-b270-462b-b332-bf0db573f724.png)

В папке компонента должны лежать только те картинки, которые к нему относятся. Эти кстати не относятся к какому либо компоненту, аватарки пользователей в настоящих проектах получают в запросах. Поэтому в этом проекте они должны лежать например в pages, рядом с данными, которые ты передаешь по дереву компонентов, и приходить в параметрах

**Comment by kate-fsd** [comment]
Параметры по умолчанию: 
- должны иметь какой то смысл. В этих текстах его нет. 
- обычно те параметры, которые имеют некоторое начальное состояние или используются наиболее часто (например для календаря isOpen=false). 
- не должны включать специфических данных (например имени и аватарки комментатора)

Для некоторых компонентов можно сделать все параметры по умолчанию, например инпут:
input({ type='text', placeholder='enter text', required=true } = {})
и вызывать его без параметров
+input();

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/132951445-4fa532c2-2ffd-4976-9078-7501b7fb8ee4.png)
![image](https://user-images.githubusercontent.com/66846004/132951454-cefe7be1-9724-459c-8a1e-577e43b491e9.png)

следи за тем чтобы в классы БЭМ не попадала всякая ерунда, например advantages__icon_with-sign-false

**Comment by kate-fsd** [comment]
Один такой компонет у тебя называется advantages - во множественном числе
![image](https://user-images.githubusercontent.com/66846004/132951582-60800328-7735-4850-ab12-f9be3e252cdc.png)

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/132951818-9785a1c5-da9d-45ae-9c17-09ce2646ac37.png)

Это не advantage, это отдельный компонент comment
https://github.com/fullstack-development/front-end-best-practices/tree/master/HTML#1.1

**Comment by kate-fsd** [comment]
Компонент должен быть самодостаточным. Так advantage выглядит без внешней обертки, явно не по макету
![image](https://user-images.githubusercontent.com/66846004/132952288-ede48da0-4b8d-4097-8b2d-6f57e2c20ea2.png)

**Comment by kate-fsd** [comment]
> Компонент должен быть самодостаточным. Так advantage выглядит без внешней обертки, явно не по макету

Здесь все в порядке, моя ошибка. Только лучше объединить несколько преимуществ в один отдельный блок

**Comment by kate-fsd** [comment]
> * должны иметь какой то смысл. В этих текстах его нет.

осталось

**Comment by kate-fsd** [comment]
Нужно ограничить количество символов в строке. Обычно 80-110, главное чтоб не приходилось сроллить в бок

**Comment by kate-fsd** [comment]
Давай пагинацию тоже сделаем более рабочей. Передавай в нее параметры - текущую страницу, количество айтемов на странице, общее количество айтемов

**Comment by kate-fsd** [comment]
> * не должны включать специфических данных (например имени и аватарки комментатора)

![image](https://user-images.githubusercontent.com/66846004/148993561-01289267-9a1a-4e0d-97d6-63f56f9034f0.png)

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/148994107-846a2e30-e08f-49c5-a964-92f167263558.png)

Кнопки соцсетей это все таки не копирайт) нужно другое название

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/148995616-3f816c53-162e-4b48-853d-031b0a93666b.png)

Мне кажется тут лучше дать другие имена инпутам. А то сначала input, внутри input-wrapper

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/148995940-53c8e628-410e-48d3-8354-8c0e5d108104.png)

Магическое число

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/148996303-fbb045b0-be2e-44c1-94af-e0751a93b3db.png)

А может это немного по другому переписать? Сразу дату установить

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/148996694-74e07a90-d0e3-421d-bf3a-5b2e5ace9397.png)

Название плохо описывает то что функция делает

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/148997316-5147fb83-6b9b-41be-bc88-ff239c4554aa.png)

Лучше не прятать, а вообще не создавать. И имя поменять

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/149000998-2dae2ce3-2dde-46e5-b93a-1a22047598c7.png)

В checked лучше boolean

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/149001551-5ce9aeef-02a2-401a-b2a0-59df2e7d91fa.png)

Лучше вынести в отдельный файл с константами

и не строкой
![image](https://user-images.githubusercontent.com/66846004/149001684-7506b5f9-520d-47c1-926b-df6ea825d87a.png)

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/149001807-3d325e93-cb5b-4475-966c-3534caaeb201.png)

Это динамические данные, они должны прийти в параметрах

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/149003500-419f1dd8-852b-4228-a2ed-4f5edb5dad80.png)

Если уж семантические компоненты содержат текст, то не надо передавать заголовок в параметрах. Если это форма логина, она ею и останется, заголовок не может измениться)

**Comment by wzdorowa** [comment]
> ![image](https://user-images.githubusercontent.com/66846004/148994107-846a2e30-e08f-49c5-a964-92f167263558.png)
> 
> Кнопки соцсетей это все таки не копирайт) нужно другое название

Это компонент копирайт) он располагается под футером, в нём лежит сторка "Copyright © 2018 Toxin отель. Все права защищены." + компонент social-button. Константу button в этом компоненте (копирайт) я определяю, чтобы записать в неё массив с данными иконок для кнопок соцсетей и затем передать эти данные в компонент social-button. Не знала правильно делаю или нет, поэтому сделала так.

**Comment by kate-fsd** [comment]
> Параметры по умолчанию:
> 
> * должны иметь какой то смысл. В этих текстах его нет.
>   ![image](https://user-images.githubusercontent.com/66846004/133079269-ba2e3682-557f-4ae3-8431-bf360c953de4.png)
> * обычно те параметры, которые имеют некоторое начальное состояние или используются наиболее часто (например для календаря isOpen=false).
> * не должны включать специфических данных (например имени и аватарки комментатора)
> 
> Для некоторых компонентов можно сделать все параметры по умолчанию, например инпут: input({ type='text', placeholder='enter text', required=true } = {}) и вызывать его без параметров +input();

![image](https://user-images.githubusercontent.com/66846004/150170983-162fc149-7ec3-4362-a452-8227a43e7643.png)

Мне кажется осталось небольшое недопонимание насчет дефолтных значений) Для динамических данных, которые приходят с сервера, не должно быть каких то значений или текста, вводящих в заблуждение. Например "несколько дней назад". На этом месте, если у тебя пошло что то не так и даты нет, лучше не выводить ничего.

![image](https://user-images.githubusercontent.com/66846004/150171267-36dcbf5b-5252-4ac2-a725-9fc6a9c2b309.png)

И в подобных местах. Если не передана подпись, пусть ее и не будет) а "Значение для выбора"  это то что совершенно не понятно пользователю, что произойдет когда ты по ней кликнешь

![image](https://user-images.githubusercontent.com/66846004/150171788-87db2fa5-fd45-476b-84ab-18b7b40083c7.png)

Тут с количеством на странице и с текущей страницей все ок, но количество айтемов не 180, ты ж не знаешь изначально сколько их будет. Подойдет 0 или ничего

**Comment by kate-fsd** [comment]
> > ![image](https://user-images.githubusercontent.com/66846004/148994107-846a2e30-e08f-49c5-a964-92f167263558.png)
> > Кнопки соцсетей это все таки не копирайт) нужно другое название
> 
> Это компонент копирайт) он располагается под футером, в нём лежит сторка "Copyright © 2018 Toxin отель. Все права защищены." + компонент social-button. Константу button в этом компоненте (копирайт) я определяю, чтобы записать в неё массив с данными иконок для кнопок соцсетей и затем передать эти данные в компонент social-button. Не знала правильно делаю или нет, поэтому сделала так.

Я о том что весь этот компонент не может называться копирайт, потому что кнопки соцсетей никакого отношения к копирайту не имеют
+social-button({ buttons })
Еще если компонент принимает массив, то тоже должен назваться social-buttons. И если данные о кнопках лежат прямо в компоненте, а не приходят сверху, странно что они тут, в copyright, а не в social-button

**Comment by kate-fsd** [comment]
> Есть проблема с диаграммой ![image](https://user-images.githubusercontent.com/66846004/150161367-c13194ea-0377-47a7-98c4-2076a4d1cee2.png)
> 
> Тут нужно подумать над тем, что произойдет если диаграмм будет несколько на странице ![image](https://user-images.githubusercontent.com/66846004/150161672-e7a85f50-d217-4f66-86b2-7a6199ec6cbe.png)

Осталось
Класс создается не для всего компонента
Зачем классу искать все слайдера на странице

**Comment by kate-fsd** [comment]
> И в подобных местах. Если не передана подпись, пусть ее и не будет) а "Значение для выбора" это то что совершенно не понятно пользователю, что произойдет когда ты по ней кликнешь

Имела в виду "". Почему бы не иметь просто чекбокс без подписей)

mixin checkbox-button({ value
Тут имя value стоит использовать по назначению, а не для подписи

**Comment by kate-fsd** [comment]
_handleSegmentMouseoute
ошибка
