### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by kate-fsd** [wzdorowa/TOXIN#39]
Не по БЭМ
![image](https://user-images.githubusercontent.com/66846004/132951975-76f8d3bd-5b52-45b8-a89b-9cc88389fa2f.png)

**Comment by wzdorowa** [comment]
> Не по БЭМ
> ![image](https://user-images.githubusercontent.com/66846004/132951975-76f8d3bd-5b52-45b8-a89b-9cc88389fa2f.png)

Повторила теорию по БЭМ. Насколько мне известно блоки можно вкладывать друг в друга. К тому же внешних отступов у них нет.

**Comment by wzdorowa** [comment]
Так как компонент переписала, структура в нём изменилась.

**Comment by kate-fsd** [comment]
Верно. Наверное смутили преимущества в отзыве) Я уже не помню что было
